# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-25 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', tinymce.models.HTMLField()),
                ('pub_date', models.DateTimeField(verbose_name=datetime.datetime(2016, 7, 25, 12, 25, 31, 890992, tzinfo=utc))),
                ('meta_title', models.CharField(max_length=250)),
                ('meta_description', tinymce.models.HTMLField()),
            ],
        ),
    ]
