# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-25 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160725_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 15, 31, 51, 768655, tzinfo=utc)),
        ),
    ]
