# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-20 12:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160725_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.FileField(max_length=250, upload_to=b'')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2016, 8, 20, 12, 16, 22, 164622, tzinfo=utc))),
                ('meta_title', models.CharField(blank=True, max_length=250)),
                ('meta_description', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 12, 16, 22, 163384, tzinfo=utc)),
        ),
    ]
