# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-20 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160820_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 13, 0, 32, 764342, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 13, 0, 32, 765568, tzinfo=utc)),
        ),
    ]
