# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-20 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20160820_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('logoclass', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 13, 18, 10, 954950, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 13, 18, 10, 956174, tzinfo=utc)),
        ),
    ]
