# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-20 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 20, 13, 18, 10, 959524, tzinfo=utc)),
        ),
    ]
